### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by amcdnl** [ngrx-utils/ngrx-utils#2]
> What's different with ngrx-actions
No need reflect-metadata as a dependency

Not true anymore ;P

Also, it would be appreciated to give some credit ;)

**Comment by sandangel** [comment]
Hi @amcdnl . I had updated the README accordingly.
Could you be more specific how I could add a credit to you. I'm pretty new to the open source world and I just don't know how to do thing right. I have a note in README that this project was inspired by your idea before but if that's not enough, please tell me.

**Comment by amcdnl** [comment]
Oh, I totally missed that at the top! Thanks so much!!! CHEERS!
