### ISSUE TITLE
Redux Dev Tools

### ISSUE THREAD

**Issue by amcdnl** [ngrx-utils/ngrx-utils#25]
> Better type inference with ofAction pipeable operator and use instanceof to filter action instead of call new Action().type. You won't have to use type cast.

The reason why I did this is because it won't work w/ Redux Dev Tools for replay.

**Comment by sandangel** [comment]
hi @amcdnl 
Correct me if I'm wrong because if user have some parameter in Action constructor like this:

```typescript
export class Login extends Action {
  readonly type = 'Login'
  constructor(public payload: User) {}
}
```

calling new Login().type without giving it a parameter is a right approach?

In the docs I have already mention that if you want to deserialize action, use ofType operator instead.

**Comment by amcdnl** [comment]
If you try to replay a action in dev tools that has an effect that uses ofAction the effect won't fire. Thats why I do the `new klass().type` so I'm comparing the strings rather than instance of

**Comment by sandangel** [comment]
Hi @amcdnl 
IMO, I think that if we want to replay an action in dev tools, we should use ofType instead. And I’m going to deprecate this operator soon when typescript 2.8 landed. Thanks for your kind explaination. I appreciate that.
