### ISSUE TITLE
RxJS 6 support?

### ISSUE THREAD

**Issue by spock123** [ngrx-utils/ngrx-utils#53]
Hi, .thanks for a great library.

Now my question: the current version breaks on RxJS6, because of exported symbols being moved in RxJS.

Yes we can use rxjs-compat but it would be nice if ngrx-utils supported rxjs6 out of the box.

Any ideas?

Cheers

```
ERROR in ./node_modules/rxjs/operators/takeUntil.js
Module not found: Error: Can't resolve 'rxjs-compat/operators/takeUntil' in '/Users/spock/project/dba/test/frontend/node_modules/rxjs/operators'
 @ ./node_modules/rxjs/operators/takeUntil.js 6:9-51
 @ ./node_modules/@ngrx-utils/store/release/@ngrx-utils/store.es5.js
```

**Comment by sandangel** [comment]
hi @spock123 , sorry for late reply. I forgot to watch this repo so there was no notification. Currently I'm working on an update version which will :

- [x] support dispatch multiple actions, 
- [x] compatible with rxjs6 and angular 6
- [x] push pipe for no zone environment.
- [ ] #52  monad pattern to abstract nested if else in ngrx selectors

Actually. I have finished all implementation but still struggle in some tests.

**Comment by sandangel** [comment]
hi @spock123 , you could try `yarn add @ngrx-utils/store@beta` now for latest build

**Comment by sandangel** [comment]
hmm, look like ng-packagr is not compatible with angular 6 yet

**Comment by spock123** [comment]
@sandangel  I'm sorry I reply this late..  thanks for the beta so far.. I am really grateful for your work. I know ng-packagr is not compatible yet, hopefully it'll come soon

**Comment by sandangel** [comment]
I’m using bazel for build now. ^^ you can try that one in beta 3

**Comment by spock123** [comment]
@sandangel 
Trying beta 3 doesn't give me no errors in Webpack, browser complains:

```
Error: StaticInjectorError(AppModule)[NgrxSelectModule -> Store]: 
  StaticInjectorError(Platform: core)[NgrxSelectModule -> Store]: 
    NullInjectorError: No provider for Store!
```

Angular 6.0.0 RC.5
NgRx/Store: 6.0.0-beta.1
Any ideas?

Cheers

**Comment by sandangel** [comment]
because you have not import StoreModule from ngrx store yet ^^

**Comment by spock123** [comment]
@sandangel  whut? I'm pretty sure I have:

My app module code: 

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';

import { Routes, Route, RouterModule, PreloadingStrategy, PreloadAllModules } from '@angular/router';

// Store
import { Store, StoreModule, MetaReducer } from '@ngrx/store';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { StoreRouterConnectingModule, RouterStateSerializer } from '@ngrx/router-store';
import { EffectsModule } from '@ngrx/effects';
import { NgrxSelectModule } from '@ngrx-utils/store';
import { reducers, effects, CustomSerializer } from './store';

// Http 
import { HttpClientModule} from '@angular/common/http';

import { SharedModule } from 'modules/shared/shared.module';
import { AppRootComponent, AppComponent } from './containers';
import { components, entryComponents } from './components';

import { routes } from './app.routes';

@NgModule({
  imports: [
    BrowserModule,
    NoopAnimationsModule,
    HttpClientModule,
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules }),
    SharedModule.forRoot(),
    StoreModule.forRoot(reducers),
    StoreRouterConnectingModule.forRoot(),
    EffectsModule.forRoot(effects),
    NgrxSelectModule,
    ENV === 'development' ? StoreDevtoolsModule.instrument() : []
  ],

  declarations: [AppRootComponent, AppComponent, ...components, ...entryComponents],
  providers: [  { provide: RouterStateSerializer, useClass: CustomSerializer }],
  entryComponents: [...entryComponents],
  bootstrap: [AppRootComponent]
})
export class AppModule {
  constructor() {}
}

```

**Comment by sandangel** [comment]
which version of ngrx you are using?
the error message mean the ngrxselectmodule could not find store service from ngrx store. Could you try remove ngrx select module and see if other service can inject store?

**Comment by spock123** [comment]
@sandangel 

```
    "@angular/*": "6.0.0-rc.5",
    "@ngrx-utils/store": "^0.11.0-beta.3",
    "@ngrx/effects": "6.0.0-beta.1",
    "@ngrx/entity": "6.0.0-beta.1",
    "@ngrx/router-store": "6.0.0-beta.1",
    "@ngrx/store": "6.0.0-beta.1",
    "@ngrx/store-devtools": "6.0.0-beta.1"
```
Other services can inject store if I remove ngrx select. Everything works without the module. It's very strange.

**Comment by sandangel** [comment]
hmm, my app work fine. Let me see it today

**Comment by spock123** [comment]
@sandangel  thank you. I'm not sure what I'm doing wrong. I also tried to clean the node_modules and reinstall everything, just in case.

**Comment by sandangel** [comment]
hi @spock123 , beta.4 is out.
Not you don't need to import NgrxSelectModule anymore because of Tree shake able provider feature in Angular v6 ^^

**Comment by sandangel** [comment]
hi @spock123 , you can try with beta.6 now

**Comment by mischkl** [comment]
Using Angular 6 RC5 here, I also get the same error with  `@ngrx-utils/store` 0.11.0-beta.6. 

```bash
Error: StaticInjectorError(AppModule)[NgrxSelectModule -> Store]: 
  StaticInjectorError(Platform: core)[NgrxSelectModule -> Store]: 
    NullInjectorError: No provider for Store!
```

Downgrading to `@ngrx-utils/store` 0.10.0 (in combination with `rxjs-compat` fixes it.

**Comment by spock123** [comment]
@sandangel  As @mischkl  wrote, beta.6 didn't fix it. 

Thanks for your work

**Comment by sandangel** [comment]
hmm, My app work fine. May be I will have to switch back to normal provider until angular 6 release.

**Comment by sandangel** [comment]
OK, I have switched back to non-tree shakable providers in angular 5 like v0.10.0  Let me know if it still not work.

**Comment by sandangel** [comment]
@spock123 , @mischkl Thanks for being patient. Sorry this bug was introduced by me when forgetting to exclude StoreModule of ngrx/store from final bundle. This bug now fixed in 
beta.9 and you can play around with it now:

https://stackblitz.com/edit/angular-rwg1fk?file=app%2Fapp.module.ts

If everything ok with you I will cut a final 0.11.0 release and update document.

**Comment by mischkl** [comment]
@sandangel Seems to work well now, thanks!

**Comment by spock123** [comment]
@sandangel  it works!! thank you so much!!!

This is great.
Your library is so needed; I can't believe why the ngrx/store team doesn't appear to want decorators that help with boilerplate code.

The @Select and @Dispatch decorators have helped me tremendously. 

Thanks again

**Comment by sandangel** [comment]
@spock123 actually using select and pluck decorators will make your class property not type safe due to typescript limitation. thats why they does not recommend it. hopefully typescript team will fix that in the future. use dispatch decorator is ok though

**Comment by sandangel** [comment]
close as 0.11.0 has released. Checkout the README and CHANGELOG for what's new.
