### ISSUE TITLE
Proposal: Wrap NgRx store as a service and put store in to Web Worker

### ISSUE THREAD

**Issue by sandangel** [ngrx-utils/ngrx-utils#6]
- [ ] Default Store object will be put into Web Worker Thread.
- [ ] Delegate ngrx/store API to ngrx-utils/store service.
- [ ] Provide a config in app root module so user can smoothly transition between ngrx/store and ngrx-utils/store.

**Comment by amcdnl** [comment]
I'm not sure you will get any benefit here. The serialization/deseralization kill any perf improvements you get from web workers.

**Comment by sandangel** [comment]
@amcdnl thanks for your advice. I'm not currently investigating on this topic. Actually I already have a Web Worker service in `@ngrx-utils/store` for running functions in web worker thread and It serves well for some of my heavy computing functions ( have not documented it yet ). May be I will review this  when Angular team start to focus more on Web Worker.

I'm going to close this issue. I wish you the best luck. ^^.

**Comment by amcdnl** [comment]
You should hit up Mike Ryan re: this.
