### ISSUE TITLE
@Dispatch with array of action doesn't trigger.

### ISSUE THREAD

**Issue by guenichone** [ngrx-utils/ngrx-utils#71]
**Versions :** 
**"@ngrx-utils/store": "^0.10.0",**
"@ngrx/effects": "^5.2.0",
"@ngrx/entity": "^5.2.0",
"@ngrx/router-store": "^5.2.0",
"@ngrx/store": "^5.2.0",
"@ngrx/store-devtools": "^5.2.0",

**How to reproduce :**
@Dispatch()
navToAll() {
  return new Navigate(['/all']);
}
^ this is working well (or any other valid action)

@Dispatch()
navToAll() {
  return [new Navigate(['/all'])];
}
^ this produces an error :

ERROR TypeError: Unexpected action in method return type, expected object of type 'Action'

I will try to dig deeper in the code soon.

**Comment by sandangel** [comment]
@guenichone you need to install v0.11.0 ^^
