### ISSUE TITLE
split ngrx-utils, so that there will be no dependency on @ngrx/store

### ISSUE THREAD

**Issue by xmlking** [ngrx-utils/ngrx-utils#72]
I am using `ngxs` but like to use `ngLet`, `untilDestroy` etc
today we `ngrx-utils` lib has hard dependency on `@ngrx/store` . would be nice to be able to use `ngrx-utils` without installing `@ngrx/store`

```
 ｢wdm｣: Failed to compile.
ERROR in node_modules/@ngrx-utils/store/src/decorators/dispatch.d.ts(1,31): error TS2307: Cannot find module '@ngrx/store'.
node_modules/@ngrx-utils/store/src/decorators/ngrx-select.d.ts(1,23): error TS2307: Cannot find module '@ngrx/store'.
node_modules/@ngrx-utils/store/src/decorators/select.d.ts(1,26): error TS2307: Cannot find module '@ngrx/store'.
```

**Comment by sandangel** [comment]
sure. I will upgrade the package to be compatible with angular 7 too.

in the meantime, you can bypass the error with `skipLibCheck` in tsconfig.json

**Comment by kbala-ami** [comment]
@sandangel I run with `skipLibCheck`, but still it throws following errors.

```
ERROR in : Can't resolve all parameters for NgrxSelectModule in /Users/kbala/Projects/BakenGoApp/node_modules/@ngrx-utils/store/ngrx-utils-store.d.ts: ([object Object], ?).
```
Please advise.

**Comment by sandangel** [comment]
hi @kbala are you sure that you put skipLibCheck in the right place? it should be in the tsconfig.app.json and tsconfig.test.json as I remember

**Comment by haleyDesignhouse** [comment]
I'm still getting this error in my Angular 6 application :( I get it to build fine, but my editor is still complaining: `property binding ngLet not used by any directive on an embedded template` as if it's not imported even though it is in my AppModule. I have NgLetModule imported from @ngrx-utils/store.

**Comment by sandangel** [comment]
@haleyDesignhouse it because your IDE doesn't recognize tsconfig.app.json. you should add the config to tsconfig.json too

**Comment by sandangel** [comment]
upgraded to angular 9 and removed all old decorators. no need to depend on `@ngrx/store`. closing
