### ISSUE TITLE
*ngLet for multiple observables not working with *ngIf 

### ISSUE THREAD

**Issue by marekdubiel** [ngrx-utils/ngrx-utils#74]
When I access multiple async pipes in ngLet, and then check them in ngIf, the component is drawn and value subscrbed is undefined. 

if I write it without ngLet,  everything works fine.

Is it bug, or am I doing something wrong?

Both cases:

```html <div class="row ">
  <ng-container *ngLet="{ all: (rolesList$ | async), user: (userRoles$ | async) } as roles">
    <pa-user-details-roles-form
      #roles
      *ngIf="roles.all && roles.user"
      [userRoles]="roles.user"
      [allRoles]="roles.all"
      [editable$]="editable$"
    ></pa-user-details-roles-form>
  </ng-container>
</div>   

--> allRoles: undefined




<div class="row ">
  <pa-user-details-roles-form
    #roles
    *ngIf="(rolesList$ | async) && (userRoles$ | async)"
    [userRoles]="userRoles$ | async"
    [allRoles]="rolesList$ | async"
    [editable$]="editable$"
  ></pa-user-details-roles-form>
</div>

--> all good

**Comment by sandangel** [comment]
could you please put your code in a code block \`\`\`html? It's pretty hard to read

**Comment by sandangel** [comment]
I guess `allRoles` is `undefined` because the initial value of the `rolesList$` observable is `undefined`.
The `*ngIf` works because if the value is `undefined`, the html template won't be rendered to the DOM, hence `allRoles` binding is not applied.

**Comment by marekdubiel** [comment]
edted, hope now it is more readable
in second case, allRoles never is asigned as undefined, because it is held back by ngIf until observable emits value, and async pipe do it's job, right? 
Shouldn't it behave like that in the first case as well?

**Comment by sandangel** [comment]
you could check by directly subscribe to roleList$ in typescript and console log to see if `undefined` was emitted.

**Comment by sandangel** [comment]
BTW, I think you should not pass an Observable as a `@Input` property like `editable$`.

**Comment by sandangel** [comment]
just another note: in the second template, you are subscribing to the `roleList$` and `userRoles$` twice.

**Comment by marekdubiel** [comment]
if roleList$ have emitted an undefined, using the second template would also produce an error, besides, it is observing a redux state and in redux tools I see the proper value. 

Exactly because of double subscription in second template i tried to use *ngLet to do it once. The component cannot be drawn before an observable emits, as its value is needed to create a form, so it has to be used twice, to check if component can be drawn and to produce a form (what exactly happens after use of second template).

I was thinking, and as both templates should produce exactly the same result, and first one fails, second one not, is it possible that the object created from two observables and async pipe contains references to an observable +  async pipe, and not actual reference to the **result** of async pipe? If that would be true, ngIf would let component to be drawn, as the roles.all and roles.user would be truthy even before the observables emit anything, and the input value would be undefined in the moment of drawing a component. 

Can't think of any other explanation as both templates should do the same thing

**Comment by sandangel** [comment]
OMG, I think I know it. can you try removing ‘#roles’ in your template? the ‘roles’ you used in the first template is actually the template variable to reference the component, not the observable result object , hence roles.all is always undefined

**Comment by marekdubiel** [comment]
YOU ARE SOO RIGHT! 
thank you!
