### ISSUE TITLE
untilDestroy doesn't work. :(

### ISSUE THREAD

**Issue by legrottagliegionata** [ngrx-utils/ngrx-utils#81]

**Comment by sandangel** [comment]
Hi, can you explain more? Maybe some sample code on Stackblitz would be super helpful

**Comment by legrottagliegionata** [comment]
The problem is Ivy

https://stackblitz.com/edit/angular-take-until-destroy-decorator-w1nwrk?embed=1&file=src/app/hello.component.ts

**Comment by sandangel** [comment]
@legrottagliegionata Oh I see. This library doesn't support angular v10 yet, which has Ivy enabled by default. I will consider adding support for v10 and beyond when Ivy becomes more stable. There are still a lot of issues with Ivy.

**Comment by SchnWalter** [comment]
If I'm not not mistaken, the only issue with Ivy was the fact that the lifecycle hooks could not be changed by the `untilDestroy` operator.

This has been fixed in Angular `v10.1.0` and it's also in `v11.0.0-next.0`.

> fix(core): Allow modification of lifecycle hooks any time before bootstrap  
> https://github.com/angular/angular/commit/737506e79cbda87d8545a663bdd618a884c2e60e

**Comment by legrottagliegionata** [comment]
In the attached project i'm using angular v11.0.0-next.0 and doesn't work untilDestroy method.

[angular-take-until-destry.zip](https://github.com/ngrx-utils/ngrx-utils/files/5225481/angular-take-until-destry.zip)

**Comment by legrottagliegionata** [comment]
Now this is my solution. TakeUntilDestroy decoretors + untilDestory method and it works correctly

```
import { Subject, MonoTypeOperatorFunction } from 'rxjs';
import { takeUntil } from "rxjs/operators";

export function TakeUntilDestroy (constructor: any): void {
  const originalDestroy = constructor.prototype.ngOnDestroy;
  if (typeof originalDestroy !== "function") {
    console.warn (`${ constructor.name } is using @TakeUntilDestroy but does not implement OnDestroy`);
  }
  let obs = constructor.prototype[destroy$];
  if (!obs) {
    constructor.prototype._takeUntilDestroy$ = new Subject ();
    constructor.prototype[destroy$] = constructor.prototype._takeUntilDestroy$.asObservable ();
    obs = constructor.prototype[destroy$];
  }

  constructor.prototype.ngOnDestroy = function (...args: any): void {
    if (typeof originalDestroy === "function") {
      originalDestroy.apply (this, args);
    }
    if (this._takeUntilDestroy$) {
      this._takeUntilDestroy$.next ();
      this._takeUntilDestroy$.complete ();
    }
  };
}

export const destroy$ = Symbol ("destroy$");

/**
 An operator that takes until destroy it takes a components this a parameter
 returns a pipeable RxJS operator.
 */
export const untilDestroy = <T> (component: any): MonoTypeOperatorFunction<T> => {
  // pipe in the takeUntil destroy$ and return the source unaltered
  if (!component[destroy$]) {
    console.warn (`Aggiungi il decoratore @TakeUntilDestroy nella classe [${ component.constructor?.name }] dato che utilizza 'untilDestroy(this)'`);
  }
  return takeUntil<T> (component[destroy$]);
}
```
`
```

@Component({
  selector: 'hello',
  template: ` `,
  styles: [``]
})
@TakeUntilDestroy
export class HelloComponent implements OnInit, OnDestroy {
  @Input() name: string; .......
```

**Comment by sandangel** [comment]
@SchnWalter @legrottagliegionata thanks for pointing this out and provided the solution. I will keep this as reference for future release. I think your solution is good, but might be a little bit complicated. Let's see if we can resolve this in a cleaner way.

**Comment by sandangel** [comment]
I have just released a new version with angular 14. I hope that will solve this issue. Please reopen if it doesn't work
