### ISSUE TITLE
Support for Angular 13

### ISSUE THREAD

**Issue by zoechi** [ngrx-utils/ngrx-utils#96]

**Comment by sandangel** [comment]
hi, @zoechi thanks for opening issue. Do you mind opening a pr for that? I'm not using Angular for a long time and don't know what have changed.

**Comment by striky1** [comment]
Hola @sandangel!

Angular 13 removed `WrappedValue` from `@angular/core`, see: https://angular.io/guide/deprecations#wrappedvalue

You are using it in:

`./node_modules/@ngrx-utils/store/__ivy_ngcc__/fesm2015/ngrx-utils-store.js:546:15-32 - Error: export 'WrappedValue' (imported as 'WrappedValue') was not found in '@angular/core'`

So, it's needed to make deep copy of `Object`: `this._latestValue` to make new reference for run change detection cycle.

striky..

**Comment by sandangel** [comment]
hmm, how should we fix that?

**Comment by striky1** [comment]
Well, if `this._latestValue` will never contains `functions` then we can do some custom function for DeepCopy like Lodash did: https://lodash.com/docs/#cloneDeep (source: https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L11087) or use Lodash as depedency.


Not sure but I think that `cloneDeep` from Lodash don't clone `functions` in `Object` (we need to test it :) ).

**Comment by Jromero-dh** [comment]
Still don't have a workaround to get this working on Angular 13?

**Comment by TheParad0X** [comment]
Same problem here! Is this going to be fixed? 🤔

**Comment by zoechi** [comment]
I switched o @ngneat/until-destroy

**Comment by TheParad0X** [comment]
I was using ngrx-utils for its convenient *nglet directive. But I think I will revert to *ngIf bevause we are migrating to Angular 13...

**Comment by striky1** [comment]
I'll try to fix it today or tomorrow.

**Comment by TheParad0X** [comment]
In the meantime I switched to https://github.com/nigrosimone/ng-let 🤷🏻‍♂️

**Comment by sandangel** [comment]
I don't know how to fix that issue though. So if anyone can have a PR I'm happy to merge.

**Comment by DerekLiang** [comment]
Can we release a version that is compatible with Angular 13 and put the issue into the backlog, since the other utility functions will work (I hope).

**Comment by sandangel** [comment]
I guess the best way is to create a library from angular 13, then add the utility functions. 
I don't use angular anymore if anyone want to take over I'm happy to merge.

**Comment by AbuHani** [comment]
Hi @sandangel, i did PR for Angular 14 can you please check it and update the package!

https://github.com/ngrx-utils/ngrx-utils/pull/105

**Comment by sandangel** [comment]
oh nice. let me check and publishing a newer version

**Comment by sandangel** [comment]
hi everyone, thanks so much for your patience and contribution. I have published a new version 0.14.0 with angular 13, 14 support. Please check it out.
